spring:
  management:
    endpoints:
      web:
        exposure:
          include: health,info,logfile
    endpoint:
      logfile:
        enabled: true
      health:
        probes:
          enabled: true
        show-details: never
  logging:
    file:
      name: /app/logs/profiler-backend.log
    level:
      root: INFO
      org.springframework.web.reactive.function.client: WARN
  config:
    import: optional:file:/config/profiler-application.yml
#    in docker, mounted from server file path in opt/

  data:
    mongodb:
      host: mongo
      port: 27017
      database: profiler
      username: profiler_app
      password: ${MONGO_PWD}
      authentication-database: profiler

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  security:
    swagger-public: false

logging:
  level:
    root: INFO
    com.emat.reapi.ai.configuration: DEBUG
    org.springframework.web.reactive.function.client: TRACE
