spring:
  config:
    import: file:///G:/javaProjects/CONFIG/profiler/profiler-application.yml

  data:
    mongodb:
      host: localhost
      port: 27018
      database: reapi_mongo_db

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  security:
    swagger-public: true
    swagger-url: http://localhost:8100

logging:
  level:
    root: INFO
    com.emat.reapi.ai.configuration: DEBUG
    org.springframework.web.reactive.function.client: TRACE
